apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  namespace: streamlit-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit-container
        image: 713386558285.dkr.ecr.us-east-1.amazonaws.com/streamlit-app:v1
        ports:
        - containerPort: 8501
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"